language: rust
rust:
  - stable
  - nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      rustup component add clippy
    fi
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo clippy -- --deny warnings
      cargo clippy --tests --all-features -- --deny warnings
    fi
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo bench --verbose
    fi

cache: cargo
