language: rust
rust:
  - stable
  - nightly

before_script:
  - rustup component add clippy
script:
  - |
    cargo clippy -- --deny warnings
    cargo clippy --tests --all-features -- --deny warnings
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clippy --benches --all-features -- --deny warnings
    fi
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo bench --verbose
    fi

cache: cargo
