language: rust
rust:
  - stable
  - nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    else
      rustup component add clippy
    fi
script:
  - cargo clippy --all-targets --all-features -- --deny warnings
  - cargo build --verbose --all --all-targets --all-features
  - cargo test --verbose --all --all-targets --all-features

cache: cargo
