[package]
name = "kdtree"
version = "0.1.0"
authors = ["Hidehito Yabuuchi <hdht.ybuc@gmail.com>"]

[dependencies]
failure = "0.1.3"
num-traits = "0.2.6"

[dev-dependencies]
noisy_float = "0.1.8"
ordered-float = "1.0.1"
